version: '3'
services:
  web:
    image: nginx:alpine
    ports:
    - "8080:80"
    volumes:
    - ./www:/var/www/html
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
  php:
    build:
      context: ./docker/php/
      dockerfile: Dockerfile-alpine
    image: mattheu/php
    volumes:
    - ./www:/var/www/html
    - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    restart: always
  db:
    image: mariadb
    restart: always
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_USER=wordpress
     - MYSQL_PASSWORD=wordpress
     - MYSQL_DATABASE=wordpress
    volumes:
     - ./database:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
  memcached:
    image: memcached:alpine
    ports:
      - "127.0.0.1:11211:11211"
